import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import { NextFont } from "next/dist/compiled/@next/font";
import Sidebar from "./../components/layouts/Sidebar";

const poppins: NextFont = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <main className="bg-primary min-h-screen">
          <Navbar />
          <Sidebar />
          <div className="">{children}</div>
        </main>
      </body>
    </html>
  );
}
